export const FETCH_USERS = 'FETCH_USERS'
export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS'


export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const FETCH_ORDERS = 'FETCH_ORDERS'