export const FETCH_USERS = 'FETCH_USERS'
export const ADD_USER = 'ADD_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS'


export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'

export const FETCH_ORDERS = 'FETCH_ORDERS'